### ISSUE TITLE
cucumber.runtime.CucumberException: Couldn't load plugin class

### ISSUE THREAD

**Issue by kps12** [reportportal/agent-java-cucumber4#20]
I was trying to upgrade cucumber to use parallel execution feature, ended up issues with report portal.

In compatibility matrix it says:

Version(s) of cucumber java and cucumber junit - 4.0.0 - 4.2.6 Tested version of cucumber agent 4.0.0

I tried to different version of cucumber 4.0.0, 4.2.3, 4.2.2, 4.2.6 with cucumber agent 4.0.0 
It says 

**cucumber.runtime.CucumberException: Couldn't load plugin class: com.epam.reportportal.cucumber.ScenarioReporter. It does not implement cucumber.api.Plugin**

	at cucumber.runtime.formatter.PluginFactory.loadClass(PluginFactory.java:176)
	at cucumber.runtime.formatter.PluginFactory.pluginClass(PluginFactory.java:163)
	at cucumber.runtime.formatter.PluginFactory.getPluginClass(PluginFactory.java:220)
	at cucumber.runtime.formatter.PluginFactory.isStepDefinitionReporterName(PluginFactory.java:203)
	at cucumber.runtime.RuntimeOptions$ParsedPluginData.addPluginName(RuntimeOptions.java:385)
	at cucumber.runtime.RuntimeOptions.parse(RuntimeOptions.java:164)
	at cucumber.runtime.RuntimeOptions.<init>(RuntimeOptions.java:107)
	at cucumber.runtime.RuntimeOptions.<init>(RuntimeOptions.java:100)
	at cucumber.runtime.RuntimeOptions.<init>(RuntimeOptions.java:96)
	at cucumber.runtime.RuntimeOptionsFactory.create(RuntimeOptionsFactory.java:23)
	at com.github.mkolisnyk.cucumber.runner.ExtendedCucumber.<init>(ExtendedCucumber.java:49)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

POM has following dependencies:

    <dependency>
        <groupId>io.cucumber</groupId>
        <artifactId>cucumber-core</artifactId>
        <version>4.2.6</version>
    </dependency>
    <dependency>
        <groupId>io.cucumber</groupId>
        <artifactId>cucumber-java</artifactId>
        <version>4.2.6</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>io.cucumber</groupId>
        <artifactId>cucumber-junit</artifactId>
        <version>4.2.6</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>io.cucumber</groupId>
        <artifactId>cucumber-testng</artifactId>
        <version>4.2.6</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>io.cucumber</groupId>
        <artifactId>cucumber-picocontainer</artifactId>
        <version>4.2.6</version>
        <scope>test</scope>
    </dependency>

    
    <dependency>
        <groupId>com.epam.reportportal</groupId>
        <artifactId>agent-java-cucumber</artifactId>
        <version>4.0.0</version>
    </dependency>

cucumber cucumber-jvm reportportal

**Comment by kaustubhshete** [comment]
any updates on this issues, we are facing similar issue.

**Comment by HardNorth** [comment]
@kps12 @kaustubhshete with 'Cucumber 4' please use **agent-java-cucumber4** dependency, and not **agent-java-cucumber**

**Comment by sushmanirvighna** [comment]
Exception in thread "main" cucumber.runtime.CucumberException: Couldn't load plugin class: org.jetbrains.plugins.cucumber.java.run.CucumberJvm5SMFormatter. It does not implement cucumber.api.Plugin

 i am facing this issue any updates will be appreciated Thank you

**Comment by HardNorth** [comment]
@sushmanirvighna, Sorry, we have nothing to do with `jetbrains` Cucumber plugin, please address this question to their community.
