### ISSUE TITLE
cucumber.runtime.CucumberException: Couldn't load plugin class: com.epam.reportportal.cucumber.StepReporter

### ISSUE THREAD

**Issue by dineshven** [reportportal/agent-java-cucumber4#9]
Could not run the test and throws the error Couldn't load plugin class: com.epam.reportportal.cucumber.StepReporter

cucumber-java version : 4.2.6
cucumber-testng : 4.2.6

**Comment by aadilc33** [comment]
Same Error 
I am facing
cucumber.runtime.CucumberException: Couldn't load plugin class: com.epam.reportportal.com.epam.reportportal.cucumber.AbstractReporter.ScenarioReporter

	at cucumber.runtime.formatter.PluginFactory.loadClass(PluginFactory.java:180)
	at cucumber.runtime.formatter.PluginFactory.pluginClass(PluginFactory.java:165)
	at cucumber.runtime.formatter.PluginFactory.getPluginClass(PluginFactory.java:222)
	at cucumber.runtime.formatter.PluginFactory.isStepDefinitionReporterName(PluginFactory.java:205)
	at io.cucumber.core.options.RuntimeOptionsBuilder$ParsedPluginData.addPluginName(RuntimeOptionsBuilder.java:218)
	at io.cucumber.core.options.RuntimeOptionsBuilder.addPluginName(RuntimeOptionsBuilder.java:73)
	at io.cucumber.core.options.CucumberOptionsAnnotationParser.addPlugins(CucumberOptionsAnnotationParser.java:96)
	at io.cucumber.core.options.CucumberOptionsAnnotationParser.parse(CucumberOptionsAnnotationParser.java:51)
	at io.cucumber.junit.Cucumber.<init>(Cucumber.java:91)
	at cucumber.api.junit.Cucumber.<init>(Cucumber.java:15)
	at Listenners.MyTestRunner.<init>(MyTestRunner.java:29)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.ClassNotFoundException: com.epam.reportportal.com.epam.reportportal.cucumber.AbstractReporter.ScenarioReporter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at cucumber.runtime.formatter.PluginFactory.loadClass(PluginFactory.java:173)
	... 24 more

**Comment by kaustubhshete** [comment]
any updates on this issues, we are facing similar issue.

**Comment by HardNorth** [comment]
@kaustubhshete please specify details. Cucumber version, runner version, RP agent version.

**Comment by aadilc33** [comment]
use 1.2.5 cucumber version groupid info.cukes
they haven't updated to latest version of cucumber
report-portal, agent-cucumber4.0.2

**Comment by HardNorth** [comment]
@aadilc33 Not quite understood what you mean. If you are using "agent-java-cucumber" version 4.0.2 and Cucumber 1.2.5, then there is already version 4.0.9 which was tested with Cucumber 1.2.6.

And this is not actually correct thread for that question.

**Comment by HardNorth** [comment]
Closed due to inactivity
